export const CHANGE_ORDER = "CHANGE_ORDER";
export const GET_TODOS = "GET_TODOS";
export const UPDATE_TODO_STATUS = "UPDATE_TODO_STATUS";
export const LOADING = "LOADING";
export const UPDATE_TODO_MESSAGE = "UPDATE_TODO_MESSAGE";
export const DELETE_TODO = "DELETE_TODO";
export const CREATE_TODO = "CREATE_TODO";